[package]
name = "kapchan"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-identity = "0.8.0"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
argon2 = "0.5.3"
base64 = "0.22.1"
chrono = { version = "0.4.31", features = ["serde"] }
deadpool = "0.10.0"
diesel = { version = "2.1.3", features = ["chrono"] }
diesel-async = { version = "0.4.1", features = ["deadpool", "mysql"] }
dotenvy = "0.15.7"
sailfish = "0.9"
serde = { version = "1.0.192", features = ["derive"] }